name: Deploy Django Project

on:
  push:
    branches:
      - main  # ветка, при пуше в которую будет деплой

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add server to known hosts
        run: ssh-keyscan -H 84.201.180.139 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: ssh -i ~/.ssh/id_rsa ubuntu@84.201.180.139 "bash ~/Browser_game/Browser_game/deploy.sh"
