# Generated by Django 5.2.6 on 2025-09-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20250910_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='miniature',
            field=models.ImageField(blank=True, null=True, upload_to='miniatures/characters/', verbose_name='Миниатюра персонажа'),
        ),
        migrations.AddField(
            model_name='characterclass',
            name='miniature',
            field=models.ImageField(blank=True, null=True, upload_to='miniatures/classes/', verbose_name='Миниатюра класса'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='miniature',
            field=models.ImageField(blank=True, null=True, upload_to='miniatures/enemies/', verbose_name='Миниатюра врага'),
        ),
        migrations.AddField(
            model_name='scene',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='Фон локации'),
        ),
    ]
