# Generated by Django 5.2.6 on 2025-09-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_character_miniature_characterclass_miniature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_alive',
            field=models.BooleanField(default=True, verbose_name='Жив'),
        ),
    ]
